In [2]:
require("readr")
require("ggplot2")
require("dplyr")

Loading required package: readr

Loading required package: ggplot2

Loading required package: dplyr


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [3]:
costs <- read_csv("costs.csv")
gates <- read_csv("gates.csv")
transactions <- read_csv("transactions.csv")

Rows: 115204 Columns: 7
── Column specification ────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): Cost_ID, Cost_Type, Route_ID, From, To
dbl  (1): Amount
dttm (1): Cost_Date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 112 Columns: 5
── Column specification ────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (4): City, Gate_Number, Route_ID, Year
num (1): Annual_Gate_Cost

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 559985 Columns: 9
── Column specification ────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (9): Transaction_ID, Booking_ID, Transaction_Date, Route_ID, Transaction...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [5]:
head(costs)
head(gates)
head(transactions)

  Cost_ID  Cost_Date           Cost_Type   Route_ID From      To      Amount
1 CO000001 2024-09-01 06:30:00 Crew        YVR-YLW  Vancouver Kelowna 1388.53
2 CO000002 2024-09-01 06:30:00 Food        yvr-ylw  Vancouver Kelowna  170.52
3 CO000003 2024-09-01 06:30:00 Fuel        YVR-YLW  Vancouver Kelowna 1401.75
4 CO000004 2024-09-01 06:30:00 Maintenance yvrylw   Vancouver Kelowna 1657.45
5 CO000005 2024-09-01 06:35:00 Crew        YLW-YYC  Kelowna   Calgary 1673.28
6 CO000006 2024-09-01 06:35:00 Food        ylwyyc   Kelowna   Calgary  221.60

  City       Gate_Number Route_ID Year      Annual_Gate_Cost
1 Abbotsford G1          yxx-yyc  2024-2025 166800
2 Calgary    B1          YYCYVR   2024-2025 373200
3 Calgary    B1          yycyyz   2024-2025 373200
4 Calgary    B1          YYCYEG   2024-2025 373200
5 Calgary    B2          yyc-ywg  2024-2025 351900
6 Calgary    B2          YYCYXE   2024-2025 351900

  Transaction_ID Booking_ID Transaction_Date Route_ID Transaction_Type
1 TX1525667      BK396819   2026-07-23 18:18 YYZYHZ   Ticket
2 TX1420893      BK245942   2026-03-14 05:23 yvr-yeg  Ticket
3 TX1313706      BK274024   2025-10-29 11:54 yvryeg   Food & Onboard
4 TX1169582      BK374084   2025-04-30 02:50 YYT-YHZ  Ticket
5 TX1378465      BK319834   01/20/2026 04:02 YYZYYC   Ticket
6 TX1133037      BK382994   2025-03-11 20:20 YQBYUL   Extra Baggage
  Membership_Tier Booking_Channel      Payment_Method Amount
1 Non-Member      Direct Web           Credit Card    $954.80
2 Blue            Corporate Portal     Credit Card    $971.17
3 Non-Member      Online Travel Agency Credit Card    $9.87
4 Silver          Direct Web           Credit Card    $744.61
5 Blue            Direct Web           Credit Card    $1,380.38
6 Blue            Direct Web           Credit Card    $45.06