In [35]:
require("readr")
require("ggplot2")
require("dplyr")
require("stringr")
require("lubridate")

Loading required package: lubridate


Attaching package: ‘lubridate’


The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union

In [83]:
costs <- read_csv("costs.csv")
gates <- read_csv("gates.csv")
transactions <- read_csv("transactions.csv")

Rows: 115204 Columns: 7
── Column specification ────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): Cost_ID, Cost_Type, Route_ID, From, To
dbl  (1): Amount
dttm (1): Cost_Date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 112 Columns: 5
── Column specification ────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (4): City, Gate_Number, Route_ID, Year
num (1): Annual_Gate_Cost

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 559985 Columns: 9
── Column specification ────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (9): Transaction_ID, Booking_ID, Transaction_Date, Route_ID, Transaction...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Cleaning costs dataset

In [77]:
costs <- costs |>
    mutate(Route_ID = toupper(Route_ID))
first <- str_extract(costs$Route_ID, "[A-Z]{3}")
second <- str_extract(costs$Route_ID, "[A-Z]{3}$")
combined <- paste0(first, '-', second)
costs$Route_ID = combined
costs

       Cost_ID  Cost_Date           Cost_Type   Route_ID From      To
1      CO000001 2024-09-01 06:30:00 Crew        YVR-YLW  Vancouver Kelowna
2      CO000002 2024-09-01 06:30:00 Food        YVR-YLW  Vancouver Kelowna
3      CO000003 2024-09-01 06:30:00 Fuel        YVR-YLW  Vancouver Kelowna
4      CO000004 2024-09-01 06:30:00 Maintenance YVR-YLW  Vancouver Kelowna
5      CO000005 2024-09-01 06:35:00 Crew        YLW-YYC  Kelowna   Calgary
6      CO000006 2024-09-01 06:35:00 Food        YLW-YYC  Kelowna   Calgary
7      CO000007 2024-09-01 06:35:00 Fuel        YLW-YYC  Kelowna   Calgary
8      CO000008 2024-09-01 06:35:00 Maintenance YLW-YYC  Kelowna   Calgary
9      CO000009 2024-09-01 06:45:00 Crew        YYZ-YYC  Toronto   Calgary
10     CO000010 2024-09-01 06:45:00 Food        YYZ-YYC  Toronto   Calgary
11     CO000011 2024-09-01 06:45:00 Fuel        YYZ-YYC  Toronto   Calgary
12     CO000012 2024-09-01 06:45:00 Maintenance YYZ-YYC  Toronto   Calgary
13     CO000013 2024-09-01 06:50:00 Crew        YLW-YVR  Kelowna   Vancouver
14     CO000014 2024-09-01 06:50:00 Food        YLW-YVR  Kelowna   Vancouver
15     CO000015 2024-09-01 06:50:00 Fuel        YLW-YVR  Kelowna   Vancouver
16     CO000016 2024-09-01 06:50:00 Maintenance YLW-YVR  Kelowna   Vancouver
17     CO000017 2024-09-01 06:50:00 Crew        YQR-YYC  Regina    Calgary
18     CO000018 2024-09-01 06:50:00 Food        YQR-YYC  Regina    Calgary
19     CO000019 2024-09-01 06:50:00 Fuel        YQR-YYC  Regina    Calgary
20     CO000020 2024-09-01 06:50:00 Maintenance YQR-YYC  Regina    Calgary
21     CO000021 2024-09-01 06:50:00 Crew        YVR-YUL  Vancouver Montreal
22     CO000022 2024-09-01 06:50:00 Food        YVR-YUL  Vancouver Montreal
23     CO000023 2024-09-01 06:50:00 Fuel        YVR-YUL  Vancouver Montreal
24     CO000024 2024-09-01 06:50:00 Maintenance YVR-YUL  Vancouver Montreal
25     CO000025 2024-09-01 06:50:00 Crew        YWG-YYZ  Winnipeg  Toronto
26     CO000026 2024-09-01 06:50:00 Food        YWG-YYZ  Winnipeg  Toronto
27     CO000027 2024-09-01 06:50:00 Fuel        YWG-YYZ  Winnipeg  Toronto
28     CO000028 2024-09-01 06:50:00 Maintenance YWG-YYZ  Winnipeg  Toronto
29     CO000029 2024-09-01 06:55:00 Crew        YUL-YQB  Montreal  Quebec City
30     CO000030 2024-09-01 06:55:00 Food        YUL-YQB  Montreal  Quebec City
⋮      ⋮        ⋮                   ⋮           ⋮        ⋮         ⋮
115175 CO115175 2026-08-31 16:40:00 Fuel        YYZ-YXU  Toronto   London
115176 CO115176 2026-08-31 16:40:00 Maintenance YYZ-YXU  Toronto   London
115177 CO115177 2026-08-31 16:45:00 Crew        YHZ-YUL  Halifax   Montreal
115178 CO115178 2026-08-31 16:45:00 Food        YHZ-YUL  Halifax   Montreal
115179 CO115179 2026-08-31 16:45:00 Fuel        YHZ-YUL  Halifax   Montreal
115180 CO115180 2026-08-31 16:45:00 Maintenance YHZ-YUL  Halifax   Montreal
115181 CO115181 2026-08-31 16:55:00 Crew        YYZ-YUL  Toronto   Montreal
115182 CO115182 2026-08-31 16:55:00 Food        YYZ-YUL  Toronto   Montreal
115183 CO115183 2026-08-31 16:55:00 Fuel        YYZ-YUL  Toronto   Montreal
115184 CO115184 2026-08-31 16:55:00 Maintenance YYZ-YUL  Toronto   Montreal
115185 CO115185 2026-08-31 17:00:00 Crew        YYZ-YHZ  Toronto   Halifax
115186 CO115186 2026-08-31 17:00:00 Food        YYZ-YHZ  Toronto   Halifax
115187 CO115187 2026-08-31 17:00:00 Fuel        YYZ-YHZ  Toronto   Halifax
115188 CO115188 2026-08-31 17:00:00 Maintenance YYZ-YHZ  Toronto   Halifax
115189 CO115189 2026-08-31 17:00:00 Crew        YYZ-YOW  Toronto   Ottawa
115190 CO115190 2026-08-31 17:00:00 Food        YYZ-YOW  Toronto   Ottawa
115191 CO115191 2026-08-31 17:00:00 Fuel        YYZ-YOW  Toronto   Ottawa
115192 CO115192 2026-08-31 17:00:00 Maintenance YYZ-YOW  Toronto   Ottawa
115193 CO115193 2026-08-31 17:50:00 Crew        YVR-YYJ  Vancouver Victoria
115194 CO115194 2026-08-31 17:50:00 Food        YVR-YYJ  Vancouver Victoria
115195 CO115195 2026-08-31 17:50:00 Fuel        YVR-YYJ  Vancouver Victoria
115196 CO115196 2026-08-31 17:50:00 Maintenance YVR-YYJ  Vancouver Victoria
115197 CO115197 2026-08-31 17:50:00 Crew        YYJ-YVR  Victoria  Vancouver
115198 CO115198 2026-08-31 17:50:00 Food        YYJ-YVR  Victoria  Vancouver
115199 CO115199 2026-08-31 17:50:00 Fuel        YYJ-YVR  Victoria  Vancouver
115200 CO115200 2026-08-31 17:50:00 Maintenance YYJ-YVR  Victoria  Vancouver
115201 CO115201 2026-08-31 18:00:00 Crew        YYZ-YOW  Toronto   Ottawa
115202 CO115202 2026-08-31 18:00:00 Food        YYZ-YOW  Toronto   Ottawa
115203 CO115203 2026-08-31 18:00:00 Fuel        YYZ-YOW  Toronto   Ottawa
115204 CO115204 2026-08-31 18:00:00 Maintenance YYZ-YOW  Toronto   Ottawa
       Amount
1       1388.53
2        170.52
3       1401.75
4       1657.45
5       1673.28
6        221.60
7       1800.44
8       1898.61
9      12105.73
10      2037.11
11     16016.15
12      9391.66
13      1458.14
14       187.03
15      1532.94
16      1540.96
17      2745.73
18       333.72
19      2923.61
20      2504.61
21     13038.49
22      1958.90
23     18272.18
24      9479.12
25      6143.00
26       780.01
27      8257.68
28      4836.95
29      1411.45
30       221.04
⋮      ⋮
115175 1418.76
115176 2215.23
115177 5955.16
115178  620.33
115179 6233.48
115180 5836.37
115181 3763.79
115182  493.61
115183 4297.42
115184 2946.95
115185 7602.09
115186  664.30
115187 8137.21
115188 6179.51
115189 1985.50
115190  176.85
115191 1933.38
115192 2422.05
115193 1400.35
115194  135.32
115195 1407.43
115196 1520.97
115197 1547.04
115198  124.68
115199 1398.98
115200 1621.09
115201 2070.73
115202  202.45
115203 1952.58
115204 2257.36

Cleaning gates dataset

In [28]:
gates <- gates |>
    mutate(Route_ID = toupper(Route_ID))
first <- str_extract(gates$Route_ID, "[A-Z]{3}")
second <- str_extract(gates$Route_ID, "[A-Z]{3}$")
combined <- paste0(first, '-', second)
gates$Route_ID = combined
gates

    City          Gate_Number Route_ID Year      Annual_Gate_Cost
1   Abbotsford    G1          YXX-YYC  2024-2025 166800
2   Calgary       B1          YYC-YVR  2024-2025 373200
3   Calgary       B1          YYC-YYZ  2024-2025 373200
4   Calgary       B1          YYC-YEG  2024-2025 373200
5   Calgary       B2          YYC-YWG  2024-2025 351900
6   Calgary       B2          YYC-YXE  2024-2025 351900
7   Calgary       B2          YYC-YQR  2024-2025 351900
8   Calgary       B3          YYC-YLW  2024-2025 340700
9   Calgary       B3          YYC-YXX  2024-2025 340700
10  Edmonton      B1          YEG-YVR  2024-2025 258800
11  Edmonton      B1          YEG-YYC  2024-2025 258800
12  Edmonton      B2          YEG-YZF  2024-2025 231900
13  Halifax       A1          YHZ-YYZ  2024-2025 247600
14  Halifax       A1          YHZ-YUL  2024-2025 247600
15  Halifax       A2          YHZ-YYT  2024-2025 231900
16  Halifax       A2          YHZ-YQM  2024-2025 231900
17  Halifax       A3          NA-NA    2024-2025 220700
18  Kelowna       A1          YLW-YVR  2024-2025 203800
19  Kelowna       A1          YLW-YYC  2024-2025 203800
20  London        B1          YXU-YYZ  2024-2025 163500
21  Moncton       B1          YQM-YHZ  2024-2025 155600
22  Montreal      D1          YUL-YVR  2024-2025 394600
23  Montreal      D1          YUL-YYZ  2024-2025 394600
24  Montreal      D2          YUL-YQB  2024-2025 373200
25  Montreal      D2          YUL-YHZ  2024-2025 373200
26  Montreal      D3          YUL-YOW  2024-2025 356400
27  Ottawa        A1          YOW-YYZ  2024-2025 226300
28  Ottawa        A1          YOW-YUL  2024-2025 226300
29  Ottawa        A2          NA-NA    2024-2025 205000
30  Prince George B1          YXS-YVR  2024-2025 156700
⋮   ⋮             ⋮           ⋮        ⋮         ⋮
83  Ottawa        A1          YOW-YYZ  2025-2026 230800
84  Ottawa        A1          YOW-YUL  2025-2026 230800
85  Ottawa        A2          NA-NA    2025-2026 208300
86  Prince George B1          YXS-YVR  2025-2026 159000
87  Quebec City   A2          YQB-YUL  2025-2026 174700
88  Regina        A2          YQR-YYC  2025-2026 163500
89  Saskatoon     A1          YXE-YYC  2025-2026 167900
90  St. John's    A2          YYT-YYZ  2025-2026 188100
91  St. John's    A2          YYT-YHZ  2025-2026 188100
92  Toronto       C1          YYZ-YVR  2025-2026 500000
93  Toronto       C1          YYZ-YYC  2025-2026 500000
94  Toronto       C2          YYZ-YUL  2025-2026 488800
95  Toronto       C2          YYZ-YOW  2025-2026 488800
96  Toronto       C3          YYZ-YHZ  2025-2026 466300
97  Toronto       C3          YYZ-YWG  2025-2026 466300
98  Toronto       C4          YYZ-YYT  2025-2026 443900
99  Toronto       C4          YYZ-YXU  2025-2026 443900
100 Vancouver     A1          YVR-YYZ  2025-2026 477600
101 Vancouver     A1          YVR-YUL  2025-2026 477600
102 Vancouver     A2          YVR-YYC  2025-2026 466300
103 Vancouver     A2          YVR-YEG  2025-2026 466300
104 Vancouver     A3          YVR-YLW  2025-2026 455100
105 Vancouver     A3          YVR-YYJ  2025-2026 455100
106 Vancouver     A4          YVR-YXY  2025-2026 427100
107 Vancouver     A4          YVR-YXS  2025-2026 427100
108 Victoria      G1          YYJ-YVR  2025-2026 176900
109 Whitehorse    G1          YXY-YVR  2025-2026 154500
110 Winnipeg      A1          YWG-YYC  2025-2026 217300
111 Winnipeg      A1          YWG-YYZ  2025-2026 217300
112 Yellowknife   A2          YZF-YEG  2025-2026 152200

Cleaning transactions dataset

In [85]:
transactions <- transactions |>
    mutate(Route_ID = toupper(Route_ID)) |>
    mutate(Booking_Channel = toupper(Booking_Channel)) |>
    mutate(Transaction_Type = toupper(Transaction_Type)) |>
    mutate(Payment_Method = toupper(Payment_Method))
first <- str_extract(transactions$Route_ID, "[A-Z]{3}")
second <- str_extract(transactions$Route_ID, "[A-Z]{3}$")
combined <- paste0(first, '-', second)
transactions$Route_ID = combined

transactions$Transaction_Date <- format(
    parse_date_time(
          as.character(transactions$Transaction_Date),
          orders = c("ymd HM", "mdy HM", "dmy HM")
        ), 
    "%Y-%m-%d %H:%M")

transactions$Amount <- as.numeric(str_replace(str_replace(transactions$Amount, "\\$", ""), ",", ""))
transactions

       Transaction_ID Booking_ID Transaction_Date Route_ID Transaction_Type
1      TX1525667      BK396819   2026-07-23 00:00 YYZ-YHZ  TICKET
2      TX1420893      BK245942   2026-03-14 00:00 YVR-YEG  TICKET
3      TX1313706      BK274024   2025-10-29 00:00 YVR-YEG  FOOD & ONBOARD
4      TX1169582      BK374084   2025-04-30 00:00 YYT-YHZ  TICKET
5      TX1378465      BK319834   2026-01-20 00:00 YYZ-YYC  TICKET
6      TX1133037      BK382994   2025-03-11 00:00 YQB-YUL  EXTRA BAGGAGE
7      TX1112418      BK332533   2025-02-12 00:00 YHZ-YYZ  CHANGE FEE
8      TX1363471      BK329720   2026-01-01 00:00 YWG-YYC  TICKET
9      TX1413482      BK440357   2026-03-04 00:00 YYC-YVR  TICKET
10     TX1056794      BK321270   2024-11-28 00:00 YLW-YVR  TICKET
11     TX1065483      BK141615   2024-12-10 00:00 YVR-YYZ  REFUND
12     TX1372980      BK123359   2026-01-13 00:00 YYC-YVR  EXTRA BAGGAGE
13     TX1111064      BK430586   2025-02-10 00:00 YYZ-YOW  EXTRA BAGGAGE
14     TX1440275      BK130032   2026-04-08 00:00 YVR-YYZ  SEAT UPGRADE
15     TX1223515      BK276119   2025-07-06 00:00 YHZ-YUL  TICKET
16     TX1353379      BK252998   2025-12-19 00:00 YYC-YVR  TICKET
17     TX1287584      BK342105   2025-09-24 00:00 YHZ-YYT  TICKET
18     TX1432586      BK292388   2026-03-28 00:00 YWG-YYC  TICKET
19     TX1420561      BK245422   2026-03-13 00:00 YYJ-YVR  TICKET
20     TX1421803      BK265785   2026-03-15 00:00 YYZ-YVR  EXTRA BAGGAGE
21     TX1419142      BK422643   2026-03-11 00:00 YOW-YUL  TICKET
22     TX1151770      BK105696   2025-04-05 00:00 YEG-YYC  EXTRA BAGGAGE
23     TX1178015      BK407007   2025-05-11 00:00 YUL-YQB  TICKET
24     TX1540389      BK141438   2026-08-10 00:00 YYT-YHZ  TICKET
25     TX1125184      BK389267   2025-03-01 00:00 YYC-YVR  EXTRA BAGGAGE
26     TX1286370      BK195346   2025-09-22 00:00 YZF-YEG  SEAT UPGRADE
27     TX1522926      BK290991   2026-07-20 00:00 YYC-YYZ  EXTRA BAGGAGE
28     TX1270029      BK357074   2025-09-01 00:00 YVR-YYJ  TICKET
29     TX1143033      BK278186   2025-03-24 00:00 YWG-YYC  FOOD & ONBOARD
30     TX1227705      BK265635   2025-07-11 00:00 YYZ-YXU  TICKET
⋮      ⋮              ⋮          ⋮                ⋮        ⋮
559956 TX1495691      BK427701   2026-06-18 00:00 YYC-YLW  TICKET
559957 TX1381539      BK135966   2026-01-24 00:00 YYZ-YHZ  TICKET
559958 TX1023335      BK160738   2024-10-10 00:00 YYC-YWG  FOOD & ONBOARD
559959 TX1101261      BK198010   2025-01-28 00:00 YOW-YYZ  TICKET
559960 TX1011955      BK113002   2024-09-22 00:00 YYZ-YHZ  EXTRA BAGGAGE
559961 TX1115922      BK109704   2025-02-17 00:00 YVR-YEG  TICKET
559962 TX1230398      BK313514   2025-07-14 00:00 YYT-YYZ  FOOD & ONBOARD
559963 TX1163161      BK154594   2025-04-21 00:00 YYJ-YVR  FOOD & ONBOARD
559964 TX1430124      BK444187   2026-03-25 00:00 YYZ-YOW  FOOD & ONBOARD
559965 TX1042025      BK265921   2024-11-07 00:00 YUL-YHZ  SEAT UPGRADE
559966 TX1084967      BK149004   2025-01-06 00:00 YVR-YEG  EXTRA BAGGAGE
559967 TX1203950      BK368565   2025-06-13 00:00 YOW-YYZ  FOOD & ONBOARD
559968 TX1083071      BK292049   2025-01-03 00:00 YYC-YXE  TICKET
559969 TX1451770      BK104257   2026-04-23 00:00 YYC-YVR  TICKET
559970 TX1327086      BK305296   2025-11-15 00:00 YYC-YVR  TICKET
559971 TX1400975      BK148278   2026-02-17 00:00 YEG-YVR  TICKET
559972 TX1256274      BK309294   2025-08-15 00:00 YOW-YYZ  TICKET
559973 TX1167482      BK105733   2025-04-27 00:00 YZF-YEG  EXTRA BAGGAGE
559974 TX1040653      BK245892   2024-11-05 00:00 YYZ-YYC  TICKET
559975 TX1286992      BK363235   2025-09-23 00:00 YYC-YYZ  TICKET
559976 TX1431095      BK281569   2026-03-27 00:00 YVR-YYC  SEAT UPGRADE
559977 TX1366684      BK383417   2026-01-05 00:00 YYC-YVR  TICKET
559978 TX1543728      BK108834   2026-08-14 00:00 YZF-YEG  FOOD & ONBOARD
559979 TX1323977      BK217758   2025-11-11 00:00 YYC-YEG  TICKET
559980 TX1161212      BK427089   2025-04-18 00:00 YYZ-YXU  TICKET
559981 TX1057608      BK116129   2024-11-29 00:00 YOW-YYZ  TICKET
559982 TX1344855      BK279337   2025-12-08 00:00 YUL-YOW  TICKET
559983 TX1102189      BK246017   2025-01-30 00:00 YLW-YVR  TICKET
559984 TX1359241      BK345688   2025-12-26 00:00 YHZ-YUL  TICKET
559985 TX1402779      BK426103   2026-02-19 00:00 YZF-YEG  TICKET
       Membership_Tier Booking_Channel      Payment_Method Amount
1      Non-Member      DIRECT WEB           CREDIT CARD      954.80
2      Blue            CORPORATE PORTAL     CREDIT CARD      971.17
3      Non-Member      ONLINE TRAVEL AGENCY CREDIT CARD        9.87
4      Silver          DIRECT WEB           CREDIT CARD      744.61
5      Blue            DIRECT WEB           CREDIT CARD     1380.38
6      Blue            DIRECT WEB           CREDIT CARD       45.06
7      Blue            DIRECT WEB           POINTS + CASH     75.00
8      Non-Member      CORPORATE PORTAL     CREDIT CARD     1231.75
9      Blue            MOBILE APP           CREDIT CARD      837.35
10     Non-Member      MOBILE APP           DEBIT            599.02
11     Blue            ONLINE TRAVEL AGENCY CREDIT CARD    -2292.03
12     Platinum        DIRECT WEB           CREDIT CARD       59.63
13     Silver          DIRECT WEB           CREDIT CARD       55.18
14     Blue            ONLINE TRAVEL AGENCY CREDIT CARD      109.33
15     Gold            MOBILE APP           CREDIT CARD      757.46
16     Blue            MOBILE APP           CREDIT CARD     1005.99
17     Silver          MOBILE APP           CREDIT CARD      822.93
18     Non-Member      DIRECT WEB           CREDIT CARD     1007.46
19     Gold            DIRECT WEB           CREDIT CARD      583.76
20     Blue            MOBILE APP           CREDIT CARD       57.74
21     Non-Member      ONLINE TRAVEL AGENCY POINTS + CASH    533.13
22     Non-Member      DIRECT WEB           DEBIT             43.13
23     Blue            DIRECT WEB           CREDIT CARD      512.03
24     Non-Member      DIRECT WEB           CREDIT CARD     1013.47
25     Non-Member      CORPORATE PORTAL     CREDIT CARD       43.59
26     Non-Member      MOBILE APP           DEBIT             50.76
27     Silver          WEBSITE              DEBIT             59.27
28     Silver          MOBILE APP           POINTS + CASH    540.80
29     Blue            MOBILE APP           POINTS + CASH     27.09
30     Silver          DIRECT WEB           DEBIT            484.80
⋮      ⋮               ⋮                    ⋮              ⋮
559956 Gold            DIRECT WEB           CREDIT CARD     728.70
559957 Non-Member      ONLINE TRAVEL AGENCY POINTS + CASH  1117.06
559958 Silver          DIRECT WEB           CREDIT CARD      21.80
559959 Non-Member      ONLINE TRAVEL AGENCY CREDIT CARD     697.70
559960 Non-Member      MOBILE APP           CREDIT CARD      48.16
559961 Non-Member      ONLINE TRAVEL AGENCY CREDIT CARD     969.27
559962 Silver          MOBILE APP           CREDIT CARD      28.60
559963 Non-Member      MOBILE APP           POINTS + CASH    13.23
559964 Non-Member      DIRECT WEB           POINTS + CASH    10.41
559965 Blue            CORPORATE PORTAL     CREDIT CARD      61.82
559966 Non-Member      DIRECT WEB           CREDIT CARD      42.70
559967 NA              MOBILE APP           CREDIT CARD      28.69
559968 Blue            ONLINE TRAVEL AGENCY CREDIT CARD     632.37
559969 Blue            CORPORATE PORTAL     CREDIT CARD     826.39
559970 Gold            ONLINE TRAVEL AGENCY DEBIT           659.53
559971 Non-Member      DIRECT WEB           DEBIT           832.48
559972 Blue            ONLINE TRAVEL AGENCY CREDIT CARD     545.52
559973 Blue            CORPORATE            CREDIT CARD      36.80
559974 Non-Member      ONLINE TRAVEL AGENCY CREDIT CARD    1634.93
559975 Non-Member      DIRECT WEB           DEBIT          2096.83
559976 Non-Member      WEBSITE              CREDIT CARD      58.80
559977 Non-Member      DIRECT WEB           TRAVEL VOUCHER  666.37
559978 Blue            DIRECT WEB           CREDIT CARD      26.45
559979 Non-Member      DIRECT WEB           DEBIT           476.88
559980 Non-Member      DIRECT WEB           TRAVEL VOUCHER  488.82
559981 Non-Member      DIRECT WEB           CREDIT CARD     519.17
559982 Non-Member      DIRECT WEB           CREDIT CARD     613.72
559983 Non-Member      DIRECT WEB           CREDIT CARD     557.37
559984 Silver          MOBILE APP           CREDIT CARD     867.80
559985 Gold            CORPORATE PORTAL     DEBIT           812.38